language: python
python:
  - "2.7"
RUN apt-get install python-prct
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - tor
      - xvfb
install:
  - pip install -r requirements.txt
  - ln -s src pybitmessage  # tests environment
  - python setup.py install
script:
  - python checkdeps.py
  - xvfb-run src/bitmessagemain.py -t
  - python setup.py test
